services:
  db:
    image: postgres:16.4
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 30

  redis:
    image: redis:7.4
    volumes:
      - redis_data:/data
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 2s
      timeout: 5s
      retries: 30

volumes:
  pg_data:
  redis_data: